"""Platform-neutral computer-control contract."""

from typing import Protocol


class ComputerController(Protocol):
    async def type_text(self, text: str) -> dict[str, str]: ...

    async def press_key(self, key: str) -> dict[str, str]: ...

    async def press_hotkey(self, keys: list[str]) -> dict[str, list[str]]: ...

    async def move_mouse(self, x: int, y: int, duration: float = 0.2) -> dict[str, int]: ...

    async def click_mouse(self, x: int | None = None, y: int | None = None, button: str = "left") -> dict[str, str]: ...

    async def scroll(self, clicks: int) -> dict[str, int]: ...

    async def capture_screenshot(self) -> dict[str, int | str]: ...
